### ISSUE TITLE
Installing Agama

### ISSUE THREAD

**Issue by Mohammad-Mardini** [GalacticDynamics-Oxford/Agama#1]
Hi everyone,
I'm trying to install Agama by its default mode, so I ran 
`python setup.py install --user`

Then I got the following error:

> Received: dyld: Library not loaded: @rpath/libpython3.6m.dylib
>   Referenced from: /Users/mardini/phd_research/Agama-master/pytest42.so
>   Reason: image not found
> From py:  Fatal Python error: PyThreadState_Get: no current thread

I would appreciate if you help me with this issue?

**Comment by eugvas** [comment]
I've seen this previously on some configurations. 
The Python library may be either statically or dynamically linked, depending on the version and system. In the setup script, we try several possible choices suggested by various configuration flags provided by distutils.sysconfig.get_config_var(...), and test if the plugin compiles and can be used with the given link options.
Apparently, in some cases, Python suggests to compile a dynamic library to be linked against, but this library is not found in the system search path (I have no idea why this option is suggested by python's sysconfig!).
You may try adding this path to the LD_LIBRARY_PATH or DYLD_LIBRARY_PATH before running the script, and see if this works.
Most likely, this path is given by "LIBDIR", i.e., you may find it out by running

python -c 'from distutils import sysconfig; print(sysconfig.get_config_var("LIBDIR"))'

**Comment by fardal** [comment]
It looks like you're using anaconda with Python 3.6 on a Mac, is this correct? I got the same problem, and seem to have worked around it enough to run Agama.

There were actually two separate problems with my setup.  Problem 1 produces the error you saw.  I believe this is an Anaconda bug and not the fault of Agama.  I was unable to link to even the example codes in the extension tutorial of the Python docs; instead I got an error similar to yours.  There are many complaints about this error message for anaconda linked with various programs, e.g. 
  https://github.com/rdkit/rdkit/issues/1617
  https://www.mail-archive.com/rdkit-discuss@lists.sourceforge.net/msg07315.html
Using a conda environment with python3.5 or 3.6.1 instead of 3.6.5 fixed this problem.  There may be other workarounds too.

After fixing that, I encountered problem 2:
```
   Expected: /Users/fardal/anaconda/envs/python35
   Received: dyld: Library not loaded: @rpath/libpython3.5m.dylib
     Referenced from: /Users/fardal/work/code/Agama/pytest42.so
     Reason: image not found
   From py:  /Users/fardal/anaconda/envs/python35
```
Though my understanding is fuzzy, I suspect this error is going to occur in all Mac anaconda installations.  I'm guessing it happens because Anaconda is not an "ordinary" python installation managed via externally configured python path/library variables. Instead it manages the environment by invoking a specific file in the Anaconda bindir.  I set runProgram in setup.py to the following and it worked:
```
def runProgram(prog):
    # return subprocess.Popen(prog, stdout=subprocess.PIPE, stderr=subprocess.STDOUT).communicate()[0].decode()
    runenv = os.environ.copy()
    if 'anaconda' in sys.executable:
        pythonroot = os.path.dirname(os.path.dirname(sys.executable))
        runenv['PYTHONHOME'] = pythonroot
        runenv['DYLD_LIBRARY_PATH'] = os.path.join(pythonroot, 'lib')
    return subprocess.Popen(prog, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, env=runenv).communicate()[0].decode()
```
Using LIBDIR as suggested above would give the same path (set it to DYLD_LIBRARY_PATH). Or these variables could be configured in the shell before running the setup.  I'm not really suggesting this be inserted in the setup script, just saying that it worked for me.

**Comment by eugvas** [comment]
The problem is indeed that the test shared library (pytest42.so) compiles but cannot be loaded because python's dynamic library is not on search path.
Actually I was able to replicate this error on Anaconda 3.6 on Linux.
The solution implemented in the most recent commit is to hard-code the path to libpythonX.Y.so into the shared library (pytest42.so and eventually agama.so), if other options fail. 
If you could check whether this works, let me know.

**Comment by Mohammad-Mardini** [comment]
Thank you so much for your help, it works fine now.
I test the installation by running:
`python setup.py test`
The following is a portion of the output:

> test_orbit_integr.exe  2.2 s, OK
test_amuse.py  0.0 s, UNKNOWN
test_user_profiles.py  0.2 s, UNKNOWN
test_math.py  0.2 s, UNKNOWN
19 TESTS PASSED, NONE FAILED, 3  UNKNOWN

> 

I hope these UNKNOWNS can't affect the output since, if yes, I will close this issue.

**Comment by Mohammad-Mardini** [comment]
Thank you for your prompt reply.

I was able to import agama, so I think everything works fine at this period of time.
` import agama  `

My main aim is to study stellar orbits over 3Gyr using AGAMA. I need to introduce myself to AGAMA (I would appreciate any kindful suggestion) and how to benefit from it.
