### ISSUE TITLE
Using different units in RAGA

### ISSUE THREAD

**Issue by dipto4** [GalacticDynamics-Oxford/Agama#12]
Hi,
I was wondering if there was way to change the value of G to use different set of units for RAGA.

Thank you.

**Comment by eugvas** [comment]
not at the moment.
while the Python interface to Agama provides some basic unit conversion facilities, the standalone codes such as mkspherical, phaseflow and raga all work in the N-body units (i.e. G=1). in practice you choose your length and velocity units, and the mass unit follows from it (for instance, 1 kpc, 1 km/s => 232500 Msun is a common choice).

**Comment by dipto4** [comment]
So when we are evolving a system with binary black holes, should the total mass of the stellar particles be set to 1 or the total mass of the stellar particles + mass of the black holes be set to 1?

Thank you.

**Comment by eugvas** [comment]
this doesn't matter; you can choose _any_ base unit for two out of three independent dimensional quantities (mass, length and velocity), and the third one should be determined from the condition G=1. So for instance you may use 1Msun as mass unit and 1 pc as length unit, then the velocity unit should be 0.0656 km/s, etc.

**Comment by dipto4** [comment]
Thank you! That really helped me!

**Comment by eugvas** [comment]
by the way, the convention G=1 is referred to as "N-body units" in the docs. In the most strict definition (e.g. Heggie&Mathieu 1986), this name also implies that the total mass of the system is 1 and the total energy is -1/4, which fully determines all three base dimensional units, but both these conditions are not required in Agama when using just G=1, which establishes only one relation between three base units (length, mass and time). In fact, the whole library is carefully designed to be as scale-invariant as possible, so that even measuring distances in km and time in seconds should not break the internal algorithms - if this doesn't hold promise, that is a bug.
