### ISSUE TITLE
Generating randomized N-body initial conditions with Agama

### ISSUE THREAD

**Issue by dipto4** [GalacticDynamics-Oxford/Agama#20]
Hi,
I was using the python interface to agama to take the output from phaseflow to generate N-body initial conditions. I was wondering if there was a way to set a random seed to generate randomized initial conditions. So far I have used ```np.random.seed()``` and ```random.seed()``` but they seem to have no effect.

Thank you.

**Comment by eugvas** [comment]
I guess this refers to the sample() methods of GalaxyModel, Density and other classes, which all use the same underlying C++ function also available in the python interface as sampleNdim(). Since it doesn't use numpy, calling numpy.random.seed() will have no effect; the C++ library itself has a built-in PRNG and its own randomize() method, but it is not exposed in the python interface.
So currently there is no provision for setting the random seed from Python - it always starts with the same seed, but if you call the same method several times in the script, the outputs will be different. This is probably the easiest way to obtain statistically independent samples.

**Comment by eugvas** [comment]
Update: in recent versions, the routine `agama.setRandomSeed()` does what its name says – changes the random seed used in sampling methods of Density, GalaxyModel, etc.
