### ISSUE TITLE
Inner cutoff radius for spherical models

### ISSUE THREAD

**Issue by dipto4** [GalacticDynamics-Oxford/Agama#24]
Hello,
I was trying to construct isotropic spherical N-body models using mkspherical. For the purposes of my simulations, I need spherical models where there are no particles present inside some inner cutoff radius. Is this possible to do with Agama? If so, how?

Thank you.

**Comment by eugvas** [comment]
no, it's not physically possible: a spherical isotropic system must have a monotonically declining density profile [Binney & Tremaine, problem 4.4]. See also section 3.2.1 in Lacroix et al. arxiv:1805.02403 for a more in-depth discussion: in fact, even a model with a very flat core, such as a generalization of the Plummer model to rho ~ (r^n+a^n)^{-5/n}, is unphysical (has negative DF) for n>2.
Agama in general and mkspherical in particular wouldn't crash or even emit a warning if the DF computed via Eddington inversion turns out to be negative, but will silently replace it with zero (I admit that at least a warning would be useful, but it seems that false alerts are too frequent - need to investigate this in depth).

**Comment by dipto4** [comment]
I should've added more context to this. For the models that I am interested in, there is an MBH present at the center. I would like to generate N-body models such that there are no particles inside the Schwarzschild radius of the MBH. Would this be possible within the Agama framework?

**Comment by eugvas** [comment]
hmm, I'd think this is such a small radius that the expected number of particles is much smaller than 1. And the easiest thing is to remove them from the snapshot manually, if any are present.
of course, then there is a much larger population of particles on orbits with small angular momenta and pericentre distances below the Schwarzschild radius (or more precisely, 4 times the Schwarzschild radius - this is the equivalent Newtonian pericentre distance for nearly parabolic orbits that will be captured on the first approach). You may wish to also manually eliminate them from the snapshot or let them be captured by the MBH as the simulation runs.

**Comment by dipto4** [comment]
Thank you!
