### ISSUE TITLE
Sampling refinement procedure error 

### ISSUE THREAD

**Issue by paula-gherghinescu** [GalacticDynamics-Oxford/Agama#30]
Hello,

I am trying to create a sample of N stars through the sample() method through the GalaxyModel object through the Python interface. However, I noticed that for some parameters of the distribution function or potential, I get the following error: **RuntimeError: Error in sample(): Error in sampleNdim: refinement procedure did not converge**.

I have seen in the math_sample.cpp source code that there exists a **maxNumIter** variable which limits the number of iterations in the recursive refinement loop. This is set to 50.

My question is: is there any way I could change that constant? Or if that is not possible/recommended what would you suggest to do instead to obtain a sample?

Thank you in advance!

Paula Gherghinescu
University of Surrey

**Comment by eugvas** [comment]
hi Paula,
I'd say the default value is high enough that it should not be hit under normal circumstances, so I suspect something must be wrong with the function being sampled (e.g. it is singular or very strongly peaked). If you send me the script with parameters that reproduce this problem, I'll try to analyze it in more detail.

**Comment by paula-gherghinescu** [comment]
Hello,

Thanks for your prompt reply! Could I send you the script via e-mail?

Best,
Paula

**Comment by eugvas** [comment]
yes, please do - my email is at the beginning of reference.pdf

**Comment by eugvas** [comment]
thanks for sending the file, I did reproduce the bug.
It is caused by a combination of several factors, one of them being a long-standing problem with the action finder that I haven't solved yet.
1) The DF being sampled has a very slow decline at large |J|, as |J|^{-3.01} - just barely above the minimum value of -3 needed for the total mass to be finite. So this part by itself is fine, though not very realistic (most of the mass sits at very large J).
2) The Staeckel action finder becomes poorly behaved for extremely large values of radii (here I'm talking of r=1e50, far larger than the Universe size!) and returns Jr=0 instead of an insanely large value.  This I haven't solved yet (of course, one could simply ban very high values of radius, but how high is too high? 1e30 is perfectly acceptable if one chooses to measure length in centimeters, which is not forbidden by any law. The library is designed to be as much scale-free as possible, so anything within the range of double precision (~1e300), or at least up to 1e100 accounting for squares and cubes in some expressions, should ideally work without problems).
3) of course, the values of DF corresponding to Jr=0 are far larger than should be, therefore the sampler is tricked into thinking that there is much more mass at large radii, places more and more emphasis on this region (discovering yet more high DF values) and in the end fails to converge.

So in your case the solution is simple - add an exponential cutoff on the DF at very large J, say, `Jcutoff=1e10` or something similar. This will not only fix the problem but also make the result more physically realistic anyway.
Eventually I will need to fix the issue with the staeckel fudge, but I am planning to implement more significant changes in it soon, so it doesn't make sense to repair something that will soon be replaced.

**Comment by paula-gherghinescu** [comment]
Thanks so much for this!
