### ISSUE TITLE
Example python scripts do not work on newer python versions

### ISSUE THREAD

**Issue by pavyamsiri** [GalacticDynamics-Oxford/Agama#34]
When I was going through the example python scripts in the py folder, I noticed that some scripts do not work on newer python versions specifically python 3.10.

For example the script example_actions_nbody.py fails because it tries to use time.clock(). The function time.clock() has been deprecated since python 3.3 and was removed in python 3.8. The alternative function is time.perf_counter() released in python 3.3.

In order to support the newer versions of python, the scripts need to be changed to avoid using deprecated/removed functions.

Should the scripts be updated to only use the newer functions or should the use of the older functions be supported still via something like `try: tbegin = time.clock() except AttributeError: tbegin = time.perf_counter()`?

It might be nice to use updated f-strings for string formatting as well instead of the old % string formatting.

**Comment by eugvas** [comment]
hi Pavadol,
thanks for reporting, indeed, example_actions_nbody.py needs a small modification – will do in the next commit. 
as for f-strings, they are not available in older versions of Python, and I am determined to maintain compatibility with Python 2 as long as there is at least one user of it (i.e. myself), so this won't fly. The other option is to use the  `"%s".format(x)` syntax, which is universally supported, but since the %-operator for strings is not going to be deprecated any time soon, I'd consider this conversion a low-priority task.
More pressing is the forthcoming deprecation of `distutils`, which are heavily used in the setup script – will need to check if `setuptools` can do the same job..

**Comment by pavyamsiri** [comment]
Thanks for responding. Just curious, when do you think the next commit will be pushed?

It makes sense to keep compatibility with Python 2 especially if you are using it.

Should I close this issue now or close it when the commit gets pushed?

**Comment by eugvas** [comment]
fair enough, the last commit was more than 7 months ago! I was waiting for something more substantial to come up, but then recalled that I already had a new example script to be included in the repo, as well as a few minor changes elsewhere. So the corrected example_actions_nbody.py is now in.

**Comment by pavyamsiri** [comment]
Thanks! I'll close the issue now.
