### ISSUE TITLE
Reading/writing snapshots with Agama

### ISSUE THREAD

**Issue by savchenkoyana** [GalacticDynamics-Oxford/Agama#52]
Hello Eugene Vasiliev,

At the moment there is no possibility to write a Nemo snapshot when your data contains more than one time step. Reading is problematic too: Agama always reads the first data item with time=0.

Do you plan to add new functionality to Agama so that it reads/writes snapshots with many times? If not, maybe a warning for `agama.readSnapshot` when snapshot contains many times would be nice

**Comment by eugvas** [comment]
indeed, the handling of N-body snapshots is pretty basic, as acknowledged in the docs. I am not planning to add the functionality for reading/writing multiple timestamps, instead one can use the Python interface for [UNSIO](https://pypi.org/project/unsio/) (the original library; its stripped-down version is used by Agama) or [PyNBody](https://pypi.org/project/pynbody/). I may add a warning when a multiple-timestamp snapshot is being read..

**Comment by eugvas** [comment]
upon further examination, it turns out that Pynbody does not support NEMO snapshots, and the Python interface for UNSIO is notoriously difficult to compile (I didn't succeed after hours of experiments). Since I suddenly needed this feature myself, I took the Python code for handling multi-snapshot NEMO files from AMUSE and reworked it into a standalone module, which does not need any third-party libraries, then included it into Agama. Now the class agama.NemoFile can be used for both reading and writing multiple snapshots.

**Comment by savchenkoyana** [comment]
That is really great news! Many thanks!

**Comment by syrte** [comment]
Just in case it might be useful to someone in the future:
I have also implemented a pure Python IO for the NEMO snapshot format with friendly user interface.
https://github.com/syrte/snapio
